services:
  - type: web
    name: kirasante-bf
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: kirasante_jwt_secret_burkina_faso_2026_kira
      - key: DATABASE_URL
        fromDatabase:
          name: kirasante-db
          property: connectionString

databases:
  - name: kirasante-db
    databaseName: kirasante
    plan: free
