const { Router } = require('express');
const router = Router();
router.use('/auth',          require('./auth.routes'));
router.use('/patients',      require('./patients.routes'));
router.use('/consultations', require('./consultations.routes'));
router.use('/vaccinations',  require('./vaccinations.routes'));
router.use('/alertes',       require('./alertes.routes'));
router.use('/sync',          require('./sync.routes'));
router.use('/ussd',          require('./ussd.routes'));
router.use('/traduction',    require('./traduction.routes'));
router.use('/dashboard',     require('./dashboard.routes'));
router.use('/districts',     require('./districts.routes'));
router.use('/recherche',     require('./recherche.routes'));
router.use('/dhis2',         require('./dhis2.routes'));
module.exports = router;
